// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSkeG8YUWCiWI8FtnmGwoXzOoYmWGNXI',
    appId: '1:584785114430:web:0fb9f583f22dc7f531e86f',
    messagingSenderId: '584785114430',
    projectId: 'projectlocker001',
    authDomain: 'projectlocker001.firebaseapp.com',
    databaseURL: 'https://projectlocker001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectlocker001.firebasestorage.app',
    measurementId: 'G-K0Y82491MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMl8aFBEuzhfgfp6lcOq-_aRnerbdIlKQ',
    appId: '1:584785114430:android:0233160a64f061f931e86f',
    messagingSenderId: '584785114430',
    projectId: 'projectlocker001',
    databaseURL: 'https://projectlocker001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectlocker001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfnJxDFnmbNCdazBg7g4KvGCHuxcAJ7dI',
    appId: '1:584785114430:ios:185189587cf7822431e86f',
    messagingSenderId: '584785114430',
    projectId: 'projectlocker001',
    databaseURL: 'https://projectlocker001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectlocker001.firebasestorage.app',
    iosBundleId: 'com.example.project002',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfnJxDFnmbNCdazBg7g4KvGCHuxcAJ7dI',
    appId: '1:584785114430:ios:185189587cf7822431e86f',
    messagingSenderId: '584785114430',
    projectId: 'projectlocker001',
    databaseURL: 'https://projectlocker001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectlocker001.firebasestorage.app',
    iosBundleId: 'com.example.project002',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSkeG8YUWCiWI8FtnmGwoXzOoYmWGNXI',
    appId: '1:584785114430:web:2bdfb08883dc6cd231e86f',
    messagingSenderId: '584785114430',
    projectId: 'projectlocker001',
    authDomain: 'projectlocker001.firebaseapp.com',
    databaseURL: 'https://projectlocker001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectlocker001.firebasestorage.app',
    measurementId: 'G-XMXGJ4MJ9Q',
  );
}
